---
layout: post
title: 'The Curious Fragility of Freedom: Tocqueville, Friedman, and Economic Liberty'
categories:
- Essays
tags:
- Economics
- Freedom
- Tocqueville
status: publish
type: post
published: true
meta:
  _edit_last: '1'
  _wp_old_slug: the-curious-fragility-of-freedom-tocqueville-friedman-and-economic-liberty
---
At the beginning of his presidency, John F. Kennedy let every nation know “that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe, in order to assure the survival and the success of liberty.” In that, he inherits the centuries old liberal struggle: the defense of freedom from its enemies and competitors. The liberal camp, though, hosts as much cacophony as it does passion. With their prioritization of liberty often comes recognition of its complexity, and so thinkers debate its justification and its best defense. Milton Friedman, a Nobel-winning economist, understandably champions the markets role in maintaining and expanding liberty. When contrasted with Alexis de Tocqueville’s liberalism, Friedman’s seems insufficient and unsatisfying. Legitimated in his shallow self-interest, man is slavish for profits, an economic brute, and his society is ripe for despotism. But as Tocqueville rightly points out, man can and should aim higher towards the common good, towards everyday virtue, because in a democracy, that’s what it means to be <em>free</em>.

Milton Friedman’s support of free enterprise stems from practical and philosophical roots, and to appreciate the role they play in conception of society, we must see how he grounds them.
<h2>Friedman’s Free Markets</h2>
Milton Friedman emphasis on the free market proceeds from, in part, a distrust of government action. He argues that when government attempts to substitute its own judgments for the judgments of free people, the results are usually disastrous. In contrast to the free market’s invisible hand, which improves the lives of people, the government’s oversized foot tramples on people’s hopes and often destroys their dreams. Empiricism buttresses his claim. He vocally decried bureaucratic inefficiency and failure in his public addresses, with particular ire for social security, the minimum wage, and Medicare. In the first place, then, Friedman is a pragmatist. Even if he were to agree that justice requires certain services or programs (which he wouldn’t), he would buck the governmental path: it would not get you where you (think you) <em>need</em> to go.

Free markets are better equipped, he claims, to meet needs. Cognizant of their inevitable imperfection, he embraces markets as hotbeds of creativity, innovation, and efficiency—three things often missing from governmental bureaucracy. Even a flawed market produces better results than arrogant experts and grasping bureaucrats. His famed pencil allegory illustrates the market’s power. Each little piece—the eraser, the lead, the wood, and even the glue—come from different countries and different producers—different cultures and different people. The market transcends geographical, ideological, and national barriers to organically meet men’s needs on a massive scale but at minimized price. Put another way, markets are better, strong, and faster.

Thus, on purely practical grounds, free markets should be prioritized. But Milton Friedman does not object to government controls solely because they are ineffective. His deeper objections flow from a moral framework. As he lays out in the first chapter:

Economic arrangements play a dual role in the promotion of a free society. On the one hand, freedom in economic arrangements is itself a component of freedom broadly understood, so economic freedom is an end in itself. In the second place, economic freedom is also an indispensable means toward the achievement of political freedom.<a href="#_ftn1">[1]</a>

This dual conception of liberty underpins Friedman’s liberalism, which is essentially a classical, Smithian liberalism.  He explains, "The heart of the liberal philosophy is a belief in the dignity of the individual, in his freedom to make the most of his capacities and opportunities according to his own lights... This implies a belief in the equality of man in one sense; in their inequality in another.”<a href="#_ftn2">[2]</a> Liberty is a constitutive element of human dignity, and a dignified life, thus, has choice. Economic liberty—that is, transactional choice—is justified than on these grounds alone: man should be free to trade on his natural endowments for whatever he chooses. But Friedman goes further, tying economic freedom to political freedom. As Milton Friedman has written, “I know of no society that has been marked by a large measure of political freedom, and that has not also used something comparable to a free market to organize the bulk of economic activity.”<a href="#_ftn3">[3]</a> Free enterprise has, to borrow Amartya Sen’s terms, both intrinsic and instrumental value; it is both a bastion and a bulwark of liberty.

As a market-advocating liberal, Friedman is persuasive. Missing in his argumentation is the intuitive step from dignity to liberty, but it is easily filled with an injection of the concept of self-government. A dignified man, essentially equal to others, merits self-governance, autonomy over himself. Another cannot control his actions or beliefs <em>a priori</em>.  Freedom is thus his right, and society must scaffold pluralism as its moral framework. Connected with above pragmatic arguments, liberty itself has, again along with Sen’s analysis, instrumental and intrinsic value: it advances human conditions with innovation and efficiency, and it realizes human existence with choice and opportunity.
<h2>Friedman’s Hope: Limited Government</h2>
Friedman’s more controversial analysis tackles public policy, or more specifically the role of government in a free society. The analysis to a point is rather simplistic: increased government intervention in the free market not only distorts it but also shrinks it. For example, a minimum wage policy, he claims, saps efficiency and constricts the employer’s choice—a practical and moral failure. More subtly, though, he advances a deeper argument. As he summarized in a TV interview while describing a previous lecture:

And I gave a talk at the Catholic University of Chile under the title ‘The Fragility of Freedom.’ The essence of the talk was that freedom was a very fragile thing and that what destroyed it more than anything else was central control; that in order to maintain freedom, you had to have free markets, and that free markets would work best if you had political freedom. So it was essentially an anti-totalitarian talk… Oh, absolutely. The emphasis of that talk was that free markets would undermine political centralization and political control.<a href="#_ftn4">[4]</a>

Friedman betrays his twin fears: political centralization and political control. He considers them dangerous but popular stepping-stones to totalitarianism. He reasoning is seen in <em>Capitalism and Freedom</em>. Friedman appreciate the necessity of states in modern politics to regulate and guard the markets, but this watchdog, he claims, is often unleashed to chase after chimerical welfare programs. In the pursuit of however beneficent agendas, societies accept or even demand centralization to ensure reach and consistency. The administrative stamp of progress often crushes individual liberty. Enter political control. The sphere of “just” political action is enlarged, effectively upending the terrain for individual action. The upshot is a collectivist mentality and an ever-expansive Centre. Collectivism saps morality, he ventures, accrediting the doctrine of “social responsibility” with the “decline in the moral climate.” He argues with the rhetorical question, “If you adopt the view that a man is not responsible for his own behavior, that somehow or other society is responsible, why should he seek to make his behavior good?”<a href="#_ftn5">[5]</a> The other effect, increased governmental action, too erodes morality, since, “Whenever we depart from voluntary cooperation and try to do good by using force, the bad moral value of force triumphs over good intentions.”<a href="#_ftn6">[6]</a> The good intentions, though, are intoxicating, especially when served by a robust state. This “tendency” ushers in more reforms and, it apparently follows, less liberty.

Friedman’s conception essentially purifies capitalistic profit maximization of negative connotation and enshrines it as the bulwark of free society. Capitalism <em>is</em> freedom, apparently. The government would have a limited role, then, an “umpire” for the game of free enterprise.

Friedman overlooks, though, that there are losers in that game—always someone and in the long run, possibly everyone. He effectively forgot the Tocquevillean lesson of moderation: unchecked capitalism can lead to materialism, which can corrode the very liberty he loves.
<h2>Tocqueville’s Liberal Democratic Theory</h2>
In many ways, Tocqueville and Friedman seem related: both prioritize liberty, both fear administrative centralization, and both recognize the despotic tendencies of democracy. An appreciation of Tocqueville’s analysis, though, renders Friedman’s myopic. He traces the tendencies Friedman bemoans and Friedman’s views as well back to their sociological source—the equality of conditions—and it is from that perspective Tocqueville defends liberty, not as a self-evident virtue, but as a potential for virtue. Thus, both Tocqueville’s perspective and his conception of freedom differentiate him from Friedman and underpin a more nuanced democratic theory, one that situates capitalism in an ordered liberty.

Whereas Friedman made intuitive and empirical claims about human nature, Tocqueville offers historical ones. Looking back through the course of modern history, he perceived the “providential fact” of democratization—both politically and, more importantly, socially. Political democracy comes in the form of democratic institutions—liberal, representative legislatures, for example—and social democracy come in the space of men’s minds: man recognizes an essential equality. This sense precipitates further social democratization and an (insatiable) drive towards equality of conditions. These twin forces present the fundamental tension of modern democracy between liberty and equality. The affection of equality is greater in democratic limes, as Tocqueville laments:

“I think that democratic communities have a natural taste for freedom; left to themselves, they will seek it, cherish it, and view and privation of it with regret. But for equality their passion is ardent, insatiable, incessant, invincible; they call for equality in freedom; and if they cannot obtain that, they still call for equality in slavery. They will endure poverty, servitude, barbarism, but they will not endure aristocracy.”<a href="#_ftn7">[7]</a>

The tone of this passage betrays his bias: Tocqueville is a liberal. He offers one explanation in a letter to Beaumont, “I have never been more profoundly convinced that [liberty] alone can give to human societies in general, and to the individuals who compose them in particular, all the prosperity and greatness which our species is capable.”<a href="#_ftn8">[8]</a> Better put, that statement matches the instrumental justification of liberty Friedman champions. But Tocqueville goes further: “Freedom is a <em>sacred</em> thing. There is one thing else that better deserves the name: that is virtue. But then what is virtue if not the free choice of what is good.”<a href="#_ftn9">[9]</a> Liberty, thus, allows for individual virtue; it is not simply beneficial to society or civilization, but also to man—it constitutes moral terrain. When government forces action, even if moral, it appropriates that ground, dissolving virtue and, in effect, upending man’s morality. The same happen when man relinquishes his liberty; he has no footing to grasp virtue. This too seems to parallel Friedman, as he ribbed the hypocrisy of forced charity, but the distinction comes with the use of “virtue,” a term which Friedman hardly uses and one he even dismissed in a televised interview.<a href="#_ftn10">[10]</a><a href="#_ftn11">[11]</a> For Tocqueville, though, liberty is essential bound to virtue, so and it is in his conception of virtue we see the contrast of his liberalism.

In <em>Democracy in America</em>, Tocqueville quotes Cotton Mather on the nature of liberty in a democratic society: “Now would I have you mistake the point of your own liberty. There is a liberty of corrupt nature, which is affected by men and beasts to do what they list; and this liberty is inconsistent with authority, impatient of all restraint… But there is a civil, a moral, a federal liberty, which is the proper end and object of authority; it is a liberty for that only which is just and good.”<a href="#_ftn12">[12]</a> Scholar Michael Barone, writing on liberty and truth, elaborates: “In the succinct formulation of Lord Action, liberty is not to be defined as the ‘power of doing what we like, but the right of being able to do what we ought.’”<a href="#_ftn13">[13]</a>
<h2>Rightly Understanding Self-Interest</h2>
Tocqueville fills in the normative void in Volume II. He writes, “It must therefore be expected that personal interest will become more than ever the principal if not the sole spring of men's actions; but it remains to be seen how each man will understand his personal interest.” Fortunately, he ventures, America have rightly understood self-interest. It “produces no great acts of self-sacrifice, but it suggests daily small acts of self-denial,” and in that cultivates a health sense of community and greater purpose. Man identifies himself with the larger whole, and collectivism—whether he knows it or not—becomes his fundamental ethos. “By itself it cannot suffice to make a man virtuous; but it disciplines a number of persons in habits of regularity, temperance, moderation, foresight, self-command; and if it does not lead men straight to virtue by the will, it gradually draws them in that direction by their habits.”<a href="#_ftn14">[14]</a> Thus, self-interest right understood trains man in democratic virtue, a collectivist ethos, which smoothes the democratic process and underpins democratic society. But Tocqueville goes further; he substantiates his preference for raising self-interest with an Aristotelian analysis of man:

Whatever elevates, enlarges, and expands the soul renders it more capable of succeeding in those very undertakings which do not concern it. Whatever, on the other hand, enervates or lowers it weakens it for all purposes, the chief as well as the least, and threatens to render it almost equally impotent for both. Hence the soul must remain great and strong, though it were only to devote its strength and greatness from time to time to the service of the body. If men were ever to content themselves with material objects, it is probable that they would lose by degrees the art of producing them; and they would enjoy them in the end, like the brutes, without discernment and without improvement.<a href="#_ftn15">[15]</a>

In the first place, this distinguishes Tocqueville from Friedman. The economist focused on the individual and the maintenance of her liberty, and he, in fact, decries collectivist mentality, as it overpowers an individual’s will. Following Tocquevillle’s observations, though, that opposition seems false: individual interest can align with collective interest, and with self-interest rightly understood it usually does. This assessment, though, comes with a normative force for Tocqueville, which further distances him from Friedman. This sense of collectivism is crucial to combat the quiet threats to liberty: individualism and materialism.
<h2>The Quiet Threats to Democracy</h2>
Both springs from the same source: equality. Uncaged from class, each man is free and able to get and do what he would like, and now that men <em>can</em> have anything, men <em>do</em> want everything, since another man may have it. You’re always concerned with keeping up with the Jones’s. He observed, “The love of well-being has now become the predominant taste of the nation; the great current of human passions runs in that channel and sweeps everything along in its course.”<a href="#_ftn16">[16]</a> This tides carries man towards commerce and industry and, more importantly, onto his own affairs, his own interests, himself. Economic concerns, according to Tocqueville, then drown out political ones. The twin evils come to the fore. With the economic mindset, individualism shuts his doors to society, so it atomizes. With thirst for physical gratification, materialism deemphasizes collectivism, so it wanes.  What’s left? A fragmented, shallow society and an enfeebled, unattended democracy.

Tocqueville contends that there is a natural disposition in democracy towards strong central power, as the economic man wants stability and the independent man feels powerless.  The abdication to central administrative power seems like a good bargain: trade an increasingly burdensome liberty for peace of mind at no loss to equality. And so Tocqueville’s analysis arrives at Friedman’s despotic nightmare, but the arc is distinct. Materialism and individualism are products of low self-interest, and both are cultivated by rampant commercialism. Unrestrained and overemphasized capitalism should be avoided, according to Tocqueville, as it will only ease the ground for despotism.  In fact, he envisioned the way in which "a natural impulse is throwing up an aristocracy out of the bosom of democracy.”<a href="#_ftn17">[17]</a> Even in the 1830s, when he himself considered American capitalism soft and beneficent, he prophesized of the rise of the manufacturers and the effectual creation of an aristocracy.

In manufacturing, as Tocqueville sees it, there is a fundamental disconnect with the “workman” and the “master.” He explains, “While the workman concentrates his faculties more and more upon the study of a single detail, the master surveys an extensive whole, and the mind of the latter is enlarged in proportion as that of the former is narrowed.”<a href="#_ftn18">[18]</a> Over time the effects grow pernicious, a developed real and psychological inequality. They live in separate realms, nearly, and “[The master] resembles more and more the administrator of a vast empire; [the workman], a brute.”<a href="#_ftn19">[19]</a> The upshot of this disconnect is a severing of humanitarian ties: “Not only are the rich not compactly united among themselves, but there is no real bond between them and the poor.”<a href="#_ftn20">[20]</a> Under the guise of economic rationality, then, the rich can abandon the poor and leave their well being to the by the “charity of the public.” He aptly summarize, “In their intense and exclusive anxiety to make a fortune they lose sight of the close connection that exists between the private fortune of each and the prosperity of all.”<a href="#_ftn21">[21]</a> Thus, rampant capitalism severs the individual from the collective, and so eases the atomization of society. The atomized society is ripe for the soft despotism.
<h2>Adjudicating the Dispute</h2>
Tocqueville’s own prose summarizes his contrast with Friedman.

<blockquote>A nation that asks nothing of its government but the maintenance of order is already a slave at heart, the slave of its own well-being, awaiting only the hand that will bind it. By such a nation the despotism of faction is not less to be dreaded than the despotism of an individual. When the bulk of the community are engrossed by private concerns, the smallest parties need not despair of getting the upper hand in public affairs. At such times it is not rare to see on the great stage of the world, as we see in our theaters, a multitude represented by a few players, who alone speak in the name of an absent or inattentive crowd: they alone are in action, while all others are stationary; they regulate everything by their own caprice; they change the laws and tyrannize at will over the manners of the country, and then men wonder to see into how small a number of weak and worthless hands a great people may fall.<a href="#_ftn22">[22]</a>
</blockquote>

This is the underbelly of capitalism Friedman masks. It erodes society and threatens liberty. Driven by shallow self-interest, man may enjoy his liberty, but it grows increasingly instrumental: a tool for the defense of his own property and for the assurance of sufficient tranquility he need to enjoy it. Tranquility, though, is a despot’s favorite sell, so this conception liberty is constantly in danger of giving way to equality and despotism. A liberal should fear that slide, not ease it. Friedman’s rightly insists on decentralization and libertarianism, but in enshrining economic rationality as the general ethos—eschewing collectivism and lauding profit maximization—he endangers the survival of liberty in an imperfect world.

In effect, the Financial Crisis of 2008 adjudicates this dispute: regrettably Tocqueville was right. A society that unleashes materialism and uncages vice, forgets, to paraphrase JFK, that those who foolishly seek power by riding the back of the tiger end up inside.

<hr size="1" /><a name="_ftn1">[1]</a> Friedman, Milton, <em>Capitalism and Freedom,</em> (Chicago 1982), Accessed Electronically on OULS. p. 8.

<a name="_ftn2">[2]</a> Friedman, <em>Capitalism and Freedom,</em> p. 195.

<a name="_ftn3">[3]</a> Friedman, <em>Capitalism and Freedom,</em> p. 9.

<a name="_ftn4">[4]</a> Friedman, Milton, as quoted in PBS, “Interview with Milton Friedman,” <em>Commanding Heights</em>, (2000). Accessed online at http://www.pbs.org/wgbh/commandingheights/shared/minitextlo/int_miltonfriedman.html

<a name="_ftn5">[5]</a> Friedman, Milton, as quoted in International Society for Individual Liberty, “Liberty Quote Library,” (2008). Accessed online at http://www.isil.org/resources/quotes-liberty.html

<a name="_ftn6">[6]</a> Ibid.

<a name="_ftn7">[7]</a> Tocqueville, Alexis de. <em>Democracy in America.</em> (tr. Reeve, Henry 1899). Volume 2, Book 2, Chapter 1. University of Virginia. http://xroads.virginia.edu/~HYPER/DETOC/toc_indx.html<em>, </em>

<a name="_ftn8">[8]</a> Tocqueville, “Letter to Beaumont,” as quoted in Lively, Jack. <em>The Sociological and Political Thought of Alexis de Tocqueville.</em> (Oxford 1962), p. 12-13.

<a name="_ftn9">[9]</a> Tocqueville, “Letter to Beaumont,” in Lively, 13.

<a name="_ftn10">[10]</a> “Free to Choose,” Video. Accessed online at http://www.dailymotion.com/video/x2n3s2_freetochoosepartie3le-pouvoir-du-ma_business

<a name="_ftn11">[11]</a> James Galbraith argued that the excessive capitalism effectively saps virtue from society; Friedman rebuffed indignantly, pointing out the lack of virtue in politics and other sphere.

<a name="_ftn12">[12]</a> Tocqueville. <em>Democracy in America</em>. Volume 1, Chapter 2

<a name="_ftn13">[13]</a> Lord Action as quoted in Novak, Michael, “Truth and Liberty: The Present Crisis in Our Culture,” The Review of Politics, (Vol. 59 1997), JSTOR,  p.21.

<a name="_ftn14">[14]</a> Tocqueville, <em>Democracy in America,</em> Volume 2, Book 2, Chapter 9.

<a name="_ftn15">[15]</a> Tocqueville, <em>Democracy in America,</em> Volume 2, Book 1, Chapter 16.

<a name="_ftn16">[16]</a> Ibid. Volume 2, Book 2, Chapter 10.

<a name="_ftn17">[17]</a> Tocqueville, <em>Democracy in America,</em> Volume 2, Book 2, Chapter 20.

<a name="_ftn18">[18]</a> Ibid.

<a name="_ftn19">[19]</a> Tocqueville, <em>Democracy in America,</em> Volume 2, Book 2, Chapter 20.

<a name="_ftn20">[20]</a> Ibid.

<a name="_ftn21">[21]</a> Tocqueville, <em>Democracy in America,</em> Volume 2, Book 2, Chapter 21.

<a name="_ftn22">[22]</a> Ibid.
