---
layout: post
title: 'The Forum Is No Agora: The Contradiction of a Marketplace of Ideas'
categories:
- Essays
tags:
- constitution
- democracy
- first amendment
- free speech
- Freedom
- politics
status: publish
type: post
published: true
meta:
  _edit_last: '1'
  _thumbnail_id: '49'
  _wp_old_slug: the-forum-is-no-agora-the-contradiction-of-a-marketplace-of-ideas
---
<a href="http://www.abhinemani.com/wp-content/uploads/2011/04/forum.png"><img class="aligncenter size-full wp-image-49" title="forum" src="http://www.abhinemani.com/wp-content/uploads/2011/04/forum.png" alt="" width="700" height="374" /></a>
<blockquote>"When men have realized that time has upset many fighting faiths, they may come to believe even more than they believe the very foundations of their own conduct that the ultimate good desired is better reached by free trade in ideas -- that the best test of truth is the power of the thought to get itself accepted in the competition of the market, and that truth is the only ground upon which their wishes safely can be carried out. That at any rate is the theory of our Constitution.” - Justice Oliver Wendell Holmes</blockquote>
In the fall of 1919, Justice Oliver Wendell Holmes <a href="http://en.wikipedia.org/wiki/Abrams_v._United_States">dissented</a> in <em>Abrams v United States</em> in what has now become a formative piece of legal scholarship in first amendment jurisprudence. This dissent attached a theory of freedom of expression to the language o the first amendment, relying upon the liberal conception of speech expounded by <a href="http://plato.stanford.edu/entries/mill/">John Stuart Mill</a>.<a title="footnote 1" href="#1">[1]</a> Mill argued that human knowledge was fallible and needed challenge in order to grow. Since we could not know what was right, nor should we take comfort in thinking we do, we needed more opposing views to constantly check the prevailing norms. More speech and so more approximation of truth. The state was conceived as a neutral arbiter; its function was the make sure society was at liberty to go in any direction it wished to go. It was a steward of the market.<a title="footnote 2" href="#2">[2]</a>

But does speech really operate in the same kind of marketplace as commercial goods? Are campaign advertisements equatable to iPods? Tying a defense of the freedom of expression to the virtues of the free market would require and exact or close mapping of their values and functioning. Holmes and Mill merely speculated about the benefits of a marketplace of ideas, but if government regulation (or lack of regulation) is to be considered similarly, then a closer inspection is necessary. We must assess how easily the <em>Forum</em> could be called the <em>Agora</em>.
<h2>Anderson's Market Norms</h2>
In her book <em><a href="http://www.amazon.com/Value-Ethics-Economics-Elizabeth-Anderson/dp/0674931904">Value in Ethics and Economics</a></em>, Elizabeth Anderson takes a close look at the mechanics of the market and in what ways its values could be applied to typically non-market goods, for example prostitution and healthcare.<a title="footnote 3" href="#3">[3]</a> To do so, she works out a set of norms, which she takes to structure market relations—that is, certain characteristics of either the participants going into the market or transactional system itself. Her framework will be a useful one is determining whether speech can function in the same way as an economic good:
<blockquote>The norms structuring market relations that govern the production, circulation, and valuation of economic goods have five features that express the attitudes surrounding use and embody the economic ideal of freedom: they are impersonal, egoistic, exclusive, want-regarding, and oriented to "exit"  rather than "voice." norms with these features, thought not governing all market transactions, are characteristic of the market. They express a shared understanding of the point and meaning of market relations recognized by every experienced participant. (emphasis mine)</blockquote>
Let us consider each of these ideals in turn.
<h3>1) Impersonal</h3>
Anderson describes the impersonal aspect of market relations, "Each party to a market transaction views his relation to the other as merely a means to the satisfaction of ends defined independent of the relationship and of the other party's end." This is to say that the economic actor functions without concern for another's interest -- only her own. In fact, this impersonal nature is held to be a democratizing feature of the market, as individuals from generally opposed groups will interact for economic reasons. As Anderson puts it, "Money income, not one's social status, characteristics, or relationships, determines one's access to commodities."

Seen this way, the marketplace of ideas seems to far more personal or at least less impersonal than the standard commodities market. Access and influence are not defined singularly by one metric. Money, connections, social position, and community value substantially affect one's ability to interact with the "marketplace of ideas." Individuals and groups who would peddle their ideas to the public enjoy enormously disparate access to the channels of mass communication. Rupert Murdoch, for instance, has television networks and newspapers at his disposal. Moreover, cultural affinities and psychological predispositions distort the way ideas are bought and sold to a greater degree than is true for commodity and service markets. Whereas the market is seen as a cultural leveler, the exchange of ideas often strengthens group polarization and fracturization. Differences among humans in such capacities as articulateness and comprehension also contribute to market failure: ideas that favor intelligent, well-spoken people — the priority accorded higher education might be one example — have a distinct and unfair advantage in the marketplace. This is to say that the marketplace of ideas would not only be shaped by brute luck differences that control the distribution of wealth, but then further maligned by that very distribution.
<h3>2) Exclusive</h3>
"A good is exclusive if access to it is limited to its purchasers," Anderson explains. "If there is no means of excluding people from enjoying a good, one cannot charge a market price for it. A good is a rival in consumption if the amount that one person consumes reduces the total amount of it available to others.”[23]  Markets for goods and services generate prices and levels of output. Scarcity, both of production and consumption resources, is the phenomenon that drives markets for goods and services.

At first, if we were to treat information as a “good” rather than an “idea," the analogy for this characteristic seems applicable. A market for ideas generates a collection of individual beliefs and, in some sense, the production of observations and arguments. There is certainly a supply and a demand for information, however quantifiable. Scarcity -- in a way -- also limits what ideas can be believed and communicated: a person must choose whether to believe something or not: she must decide which few ideas from a nearly infinite pool will command her finite attention.

As Sunstein describes in <a href="http://www.littlemag.com/mar-apr01/cass.html">"The Future of Free Speech,"</a> this phenomenon is becoming increasingly apparent in light of modern technologies, where he cites MIT professor Nicholas Negroponte phrase, "enthusiasm for 'the Daily Me'.  Consumers now have seemingly complete control over the information they confronted. Whereas "general interest intermediaries" such as newspapers or nightly news programs would present an aggregation of multiple topics, points of view, and speakers, the internet allows individuals to construct their own information silo:
<blockquote>In such a system, the market for information would be perfected in the sense that consumers would be able to see exactly what they want, no more and no less. When filtering is unlimited, people can decide, in advance and with perfect accuracy, what they will and will not encounter. They can design something very much like a communications universe of their own choosing.[25]</blockquote>
Challenges still remain for the full realization of 'the Daily Me' and the free market analogy. Prices and scarcity seem to be at best roughly mapped. The production of an idea does not deplete resources available to the producer as occurs when production priorities are established regarding goods and services. In fact, more often the production of an idea creates additional intellectual resources that facilitate future production. Modern centers of innovation are living examples of this point. Mill's defense of free expression relies on this notion, since it aspires to approach truth with more and more speech. Similarly, when one consumer “buys” an idea the supply of that idea available to other consumers is not thereby diminished; in a way, it is bolstered. As Anderson explains, ideas would be a kind of "shared" not rival good: "Shared goods, by contrast, are not rival. I do not lose, but rather enhance, my pleasure in a joke by conveying it to others."[26]  In these respects, the phenomenon of scarcity does not determine how ideas are socially ordered in quite the way it determines the allocation and distribution of conventional goods and services.
<h3>3) Egoistic</h3>
One might respond that dissonance between consumer and producer power in this market merely helps it meet the necessary description of "egoistic." "Each party in a market is expected to take care of herself," Anderson writes, and so we might say that the siloed consumer made her own bed. Her choices were a reflection of her autonomy. In <em><a href="http://www.amazon.com/Nudge-Improving-Decisions-Health-Happiness/dp/0300122233">Nudge</a></em>, Sunstein argues that the traditional defense of free choice misses some structural threats to autonomy.[28] We must look not just at a choice but behind it, and see the impact societal norms and roles have on individual autonomy and preferences. Martha may drink a particular beverage because she was part of group and that’s just what they did – it was a societal norm. Now what if discrimination or xenophobia was a norm in her society? According to Sunstein’s definition of autonomy – an individual being able to choose reflectively and deliberately from a reasonably good set of options – the close-mindedness is intensively problematic. Martha isn’t say exposed to other cultures, and she never doubts her race is the best. Her questioning might even be ridiculed, and so she doesn’t. Considering the filtering and group polarization possible in new media, this threat seems quite real.
<h3>4) Want-regarding</h3>
Aside from the threat to autonomy, the emphasis on consumer choice in the ideas market may distort it or damage the exchange of ideas, as it would need to be a "want-regarding institution." Anderson explains this kind of institution as one that "responds to 'effective demand' -- desires backed by the ability to pay for things."[29] In the market, effective demand is often seen through substitution effects, the effect observed with the changes in relative prices of goods. Having goods of different quality and price should help a market achieve efficiency. People will compromise on their wants slightly for a lower cost. But there is no equivalent bargaining in the ideas market. The very concept of “price” is problematic when the object of consumption is ideas. What is it that a person must pay in order to “consume” an idea other than the opportunity to believe conflicting ideas? In this way, the ideas market lacks the tools to effectively measure whether individual's wants are being met.

Moreover, seen as a want-regarding institution, this market in effect seems wholly anathema to the defenses propagated by Holmes and Mill provide. "Commodities are exchanged without regard for the reasons people have for wanted them," Anderson adds, "Since it offers no means for discriminating among the reasons people have for wanting or providing things, it cannot function as a forum for the justification of the principles about the things traded on."[30]  In this regard, a commodity or service market lacks a normative dimension, and conflict and disagreement are to be avoided. Money, preference, and supply are dispositive. But, according to Mill, the marketplace of ideas should foster disagreement, with bad ideas coming up against good ones to keep us moving towards truth. We then would not want listeners and readers to be looking simply for ideas that will best serve their personal needs narrowly conceived; nor should they be complacent in their beliefs. We also expect consumers of ideas to believe some things they would not want to. For both Holmes and Mill, the social value of ideas lies to a large extent in how their production and consumption generates benefits over time for persons other than the immediate producers and consumers. But then it seems misguided to place so much faith an institute designed for immediate preference realization.
<h3>5) Oriented to Voice &amp; Exit</h3>
Finally come the concepts of "exit" and "voice" in a market. "Individuals influence the provision and exchange of commodities mainly through 'exit,' not 'voice,' Anderson argues citing Albert O. Hirschman's work, <a href="http://en.wikipedia.org/wiki/Exit,_Voice,_and_Loyalty">"Exit, Voice, and Loyalty.”</a> The exit option, according to Hirschman, is when an individual simply stops buying a business's products or services or stops participating in an organization with which she is dissatisfied. Consumers in a commodities market can avail themselves of "exit." For example, if a consumer does not like the new and improved <a href="http://www.pizzaturnaround.com/">Dominos Pizza</a>, she can exercise her exit option, switch to Pizza Hut, and leave it to the former to figure out why.

"Voice" is the direct statement of an interest, preference, or dissatisfaction, while still attached or engaged to a group. If I am dissatisfied with the college I attend, I can run for student government, hold a position on the governing council, and lobby for any desired changes I'd like to see at the school. Any resulting improvements in the organization benefits me as well as my classmates. To "Exit" would be to transfer to a different college. Thus, in comparison to exit, voice is the more participatory method of providing feedback, and expressing one's preferences and values, to an organization. With exit, improvement of the exited organization comes about, if at all, courtesy of the invisible hand, and any such improvement does not redound to the benefit of the exiting consumer. Anderson describes the relationship between exit and voice in the commodities market: "The counterpart to the customer's freedom to exit a trading relationship is the owner's freedom to say 'take it or leave it.' The customer has no voice, no right to directly participate in the design of the product or to determine how it is marketed." The invisible hand of the free market acts as the feedback mechanism, as, they say, consumers vote with their wallets.

But this system of exit and voice seems altogether contradictory for a system of free expression. Considering the example of a consumer watching a media news outlet, the analogy can stand up in terms of exit: she can change the channel. Following market norms, however, this would suggest that the media outlet needs to change its coverage or content, if that taste became widespread, that it should follow the consumers who exited. Yet, both Holmes and Mill seem committed to the virtue of a diverse space for free speech, and certainly -- as we will return to -- a pluralistic democracy would benefit from the multiplicity of ideas. If the consumer is encouraged to "exit" when confronted with unwanted viewpoint, then she would merely seek to reaffirm her potentially misguided or discriminatory viewpoints. This seems to turn democracy against itself, as the majority opinions shape the public forum and slowly pervade the realm of deliberation. In effect, this model threatens to realize the French Observer <a href="http://en.wikipedia.org/wiki/Alexis_de_Tocqueville">Alexis de Tocqueville's</a> fear of the media's courtier spirit and democracy's tyranny of the majority:
<blockquote>"A newspaper can survive only on the condition of publishing sentiments or principles common to a large number of men... The more equal the conditions of men become and the less strong men individually are, the more easily they give way to the current of the multitude and the more difficult it is for them to adhere by themselves to an opinion which the multitude discard.”</blockquote>
"Exit" would harmful for a democratic body, and the state might need to enact legislative to mitigate its damage. Thus, if a standard market emphasizes the "exit" mechanism, and a passive role for a consumer, it seems inapplicable for a system of free speech.

On the other hand, "voice" seems much more like the norm a free speech market should be promoting. The commitment shown by the school board member evidences a connection to the organization, a willingness to hear opposing ideas, and an interest to enhance the institution as her own standing.
<h2>Conclusion</h2>
These comparisons suggest that the standard norms in commodities market are inapplicable for a market for ideas. In every substantive way, ideas do not seem to function in a market, at all; the term "marketplace of ideas" seems contradictory. It's time we abandon the metaphor as unfit and unwise, and consider instead how we want to value, order, and protect our First Freedom.

<hr />

<h3>Notes</h3>

<a name="1">[1]</a> Mill set the boundary at the point where speech or writing was an incitement to violence. He was also clear that his arguments for freedom only applied to ‘human beings in the maturity of their faculties’. Paternalism – that is, coercing someone for their own good – was in his opinion appropriate towards children, and, more controversially, towards ‘those backward states of society in which the race itself may be considered in its nonage’. But it was not appropriate towards adult members of a civilised society: they should be free to make their own minds up about how to live. They should also be free to make their own mistakes.

<a name="2">[2]</a> This very much aligns with the positive and negative view of rights propagated by Isaiah Berlin.[18] Individuals were protected within their own sphere of negative rights -- from intrusion of the state into their private affairs -- and the state had some control in positive rights, namely political participation. In terms of the first amendment, this meant that one was protected inside one's autonomous zone by libel and privacy laws, but outside it, in the combat zone, one was free to say anything one pleased.

<a name="3">[3]</a> The efficacy of market mechanisms as a comprehensive means of social ordering -- in for speech or for other goods -- run into trouble when considering market failure. As Joseph Stiglitz explains in his <em>Making Globalization Work</em>, markets are imperfect. Information asymmetry distorts markets. Collective behavior --  fractionalized interest, group polarization, etc -- can also distort markets. So too can free riders: persons who are in a position to benefit from the transactions of others without having to pay the price. In most speech settings, the audience could fairly be described as a convention of free riders. A different type of externality undermines efficiency when the full levy of social costs cannot practically be observed, measured, or assessed against those who engage in the activity. Cost and benefit do not always accurately come in to play. Careful attention to the features and characteristics of the marketplace under consideration is therefore warranted.
